spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot?characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat,wall,log4j
    #最大活跃数
    maxActive: 20
    #初始化数量
    initial-size: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCahe,并且指定每个连接PSCahe的大小
    pool-prepared-statements:
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionPropertiess属性来打开mergeSql功能;慢sql记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.showSqlMillis=5000
    minldel: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  jpa:
    database: MySql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy


